//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConfigurePart
    {
        public int id { get; set; }
        public int ComputerConfigurationId { get; set; }
        public int ComputerPartId { get; set; }
    
        public virtual tblComputerConfiguration tblComputerConfiguration { get; set; }
        public virtual tblComputerPart tblComputerPart { get; set; }
    }
}
